# Generated by Django 5.0.6 on 2026-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_cachedhospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Orthopedist', 'Orthopedist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Gynecologist', 'Gynecologist'), ('ENT Specialist', 'ENT Specialist'), ('Dentist', 'Dentist'), ('Ophthalmologist', 'Ophthalmologist'), ('Urologist', 'Urologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Oncologist', 'Oncologist')], default='General Physician', max_length=100),
        ),
    ]
