# Generated by Django 5.2.15 on 2026-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_is_verified_doctor_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
    ]
