# Generated by Django 5.2.15 on 2026-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_cachedquery_geocodingcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedhospital',
            name='facility_type',
            field=models.CharField(default='Hospital', max_length=50),
        ),
    ]
