# Generated by Django 5.2.15 on 2026-06-24 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_cachedhospital_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_mode_preference',
            field=models.CharField(choices=[('VC', 'Video Consultation'), ('In-Person', 'In-Person Consultation'), ('Both', 'Both (Video & In-Person)')], default='Both', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctor')),
            ],
        ),
    ]
