# Generated by Django 5.2.15 on 2026-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_appointment_mode_preference_doctor_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slot_duration',
            field=models.PositiveIntegerField(default=15, help_text='Duration of one patient timing slot in minutes'),
        ),
    ]
