# Generated by Django 5.2.15 on 2026-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_slot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='registration_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of registration with the Medical Council', null=True),
        ),
    ]
