# Generated by Django 5.2.15 on 2026-07-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctor_registration_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
