# Generated by Django 5.2.15 on 2026-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctor_age_doctor_gender_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedhospital',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cachedhospital',
            name='lng',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cachedquery',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cachedquery',
            name='lng',
            field=models.FloatField(db_index=True),
        ),
    ]
