# Generated by Django 5.2.15 on 2026-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_cachedhospital_lat_alter_cachedhospital_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.PositiveIntegerField(default=500, help_text='Consultation fee in INR (₹)'),
        ),
    ]
